apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: great-void-battle-ingress
  namespace: great-void-battle
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  - host: gvb.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: great-void-battle-api
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: great-void-battle-app
            port:
              number: 80
